# Generated by Django 4.2.1 on 2026-04-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('device_code', models.CharField(help_text='设备编号', max_length=64, unique=True, verbose_name='设备编号')),
                ('device_name', models.CharField(help_text='设备名称', max_length=64, verbose_name='设备名称')),
                ('model', models.CharField(blank=True, help_text='型号', max_length=64, null=True, verbose_name='型号')),
                ('specification', models.CharField(blank=True, help_text='规格', max_length=128, null=True, verbose_name='规格')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', help_text='设备状态（0正常 1停用）', max_length=1, verbose_name='设备状态（0正常 1停用）')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
                'db_table': 'app_device',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
