# Generated by Django 4.2.1 on 2026-04-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_nurse_dept', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('object_name', models.CharField(help_text='姓名', max_length=32, verbose_name='姓名')),
                ('object_phone', models.CharField(help_text='手机号', max_length=11, verbose_name='手机号')),
                ('object_gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='0', help_text='性别', max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(blank=True, help_text='身份证号', max_length=18, null=True, verbose_name='身份证号')),
                ('object_birthday', models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期')),
                ('object_address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('object_remark', models.CharField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('service_status', models.CharField(choices=[('0', '正常'), ('1', '暂停'), ('2', '终止')], default='0', help_text='状态', max_length=1, verbose_name='状态')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('nurse', models.ForeignKey(blank=True, db_constraint=False, help_text='责任长护师', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nurse.nurse', verbose_name='责任长护师')),
                ('nurse_dept', models.ForeignKey(blank=True, db_constraint=False, help_text='所属机构', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nurse_dept.nursedept', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '服务对象管理',
                'verbose_name_plural': '服务对象管理',
                'db_table': 'app_service_object',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
