# Generated by Django 4.2.1 on 2026-04-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseDept',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('dept_name', models.CharField(help_text='部门名称', max_length=64, verbose_name='部门名称')),
                ('dept_code', models.CharField(blank=True, help_text='部门编码', max_length=64, null=True, unique=True, verbose_name='部门编码')),
                ('sort', models.IntegerField(default=1, help_text='显示排序', verbose_name='显示排序')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', help_text='状态（0正常 1停用）', max_length=1, verbose_name='状态（0正常 1停用）')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='空表示顶级部门', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app_nurse_dept.nursedept', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '长护师-部门',
                'verbose_name_plural': '长护师-部门',
                'db_table': 'app_nurse_dept',
                'ordering': ('sort', '-create_datetime'),
            },
        ),
    ]
