# Generated by Django 4.2.1 on 2026-04-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_nurse_dept', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('nurse_name', models.CharField(help_text='姓名', max_length=10, verbose_name='姓名')),
                ('nurse_code', models.CharField(help_text='编号', max_length=64, unique=True, verbose_name='编号')),
                ('nurse_role', models.CharField(blank=True, help_text='角色', max_length=64, null=True, verbose_name='角色')),
                ('nurse_phone', models.CharField(blank=True, help_text='手机号', max_length=11, null=True, verbose_name='手机号')),
                ('nurse_status', models.CharField(choices=[('0', '在职'), ('1', '离职')], default='0', help_text='在职状态（0在职 1离职）', max_length=1, verbose_name='在职状态（0在职 1离职）')),
                ('nurse_remark', models.CharField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('nurse_dept', models.ForeignKey(blank=True, db_constraint=False, help_text='所属机构', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_nurse_dept.nursedept', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '长护师人员',
                'verbose_name_plural': '长护师人员',
                'db_table': 'app_nurse',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
