# Generated by Django 4.2.1 on 2026-04-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sop',
            fields=[
                ('id', utils.models.SnowflakeIDField(primary_key=True, serialize=False)),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('title', models.CharField(help_text='SOP标题', max_length=255, verbose_name='SOP标题')),
                ('content_html', models.TextField(blank=True, help_text='SOP内容', null=True, verbose_name='SOP内容')),
                ('video_url', models.CharField(blank=True, help_text='视频URL', max_length=512, null=True, verbose_name='视频URL')),
                ('analysis_result', models.JSONField(blank=True, help_text='分析结果', null=True, verbose_name='分析结果')),
                ('analysis_status', models.CharField(choices=[('pending', '待分析'), ('running', '分析中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='分析状态')),
                ('analysis_error', models.TextField(blank=True, help_text='错误信息', null=True, verbose_name='错误信息')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'SOP管理',
                'verbose_name_plural': 'SOP管理',
                'db_table': 'app_sop',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
